[[plugins]]
repo = 'scrooloose/nerdtree'

#[[plugins]]
#repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
