# [[plugins]]
# repo = 'scrooloose/nerdtree'

#[[plugins]]
# repo = 'vim-scripts/forcia'
#repo = 'forcia'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

#E[[plugins]]
#Erepo = 'junegunn/fzf.vim'
#Edepends = 'fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case -- '.shellescape(<q-args>), 1,
  \   fzf#vim#with_preview(), <bang>0)
'''
#	command! -bang -nargs=* Rg
#		\ call fzf#vim#grep(
#		\   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
#		\   <bang>0 ? fzf#vim#with_preview('up:60%')
#		\           : fzf#vim#with_preview('right:50%:wrap', '?'),
#		\   <bang>0)

#[[plugins]]
#repo = 'jremmen/vim-ripgrep'

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

# snippet
# https://zenn.dev/yano/articles/vim_plugin_top_10#ultisnips
# https://zenn.dev/shougo/articles/snippet-plugins-2020
# を参考にcoc-neosnippet( https://github.com/neoclide/coc-snippets )から ultisnipsへ 移行する
# neovimではultisnipsが遅いという報告があるので、様子を見てcoc-snippetに戻す
# https://zenn.dev/shougo/articles/snippet-plugins-2020#ultisnips
# https://github.com/neovim/neovim/issues/5702
## snipet engine
[[plugins]]
repo = 'SirVer/ultisnips'

## snippet definitions
[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'APZelos/blamer.nvim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo ='kristijanhusak/defx-icons'

[[plugins]]
repo ='kristijanhusak/defx-git'
hook_add = '''
	let g:defx_git#indicators = {
		\ 'Modified'  : '+',
		\ 'Staged'    : '●',
		\ 'Untracked' : '?',
		\ 'Renamed'   : '➜',
		\ 'Unmerged'  : '═',
		\ 'Deleted'   : 'x',
		\ 'Unknown'   : '?'
		\ }
'''

[[plugins]]
repo ='Shougo/defx.nvim'
on_cmd = 'Defx'
depends = ['defx-icons', 'defx-git']
hook_add = '''
	nnoremap <silent> <Space>f :<C-u>Defx `expand('%:p:h')` -search=`expand('%:p')`<CR>
	nnoremap <silent> <Space>d :<C-u>Defx -listed -columns=icons:indent:filename:type`<CR>
'''

[[plugins]]
repo ='tpope/vim-surround'

# 使いたいがエラー出るのでコメントアウト
# [[plugins]]
# repo ='skanehira/jumpcursor.vim'


[[plugins]]
repo = 'phaazon/hop.nvim'
