# 初期読込の高速化
[[plugins]]
repo = 'flowtype/vim-flow'
on_ft = ['javascript']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['javascript']

[[plugins]]
repo = 'heavenshell/vim-jsdoc'
on_ft = ['javascript']

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = ['python']

[[plugins]]
repo = 'davidhalter/jedi'
on_ft = ['python']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'scrooloose/vim-slumlord'
on_ft = ['plantuml', 'uml']

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['plantuml', 'uml']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md']
