-- -- https://github.com/williamboman/mason.nvim
-- require("mason").setup()
-- -- https://github.com/williamboman/mason-lspconfig.nvim
-- require("mason-lspconfig").setup {
-- 	ensure_installed = {
-- 		"lua_ls", -- lua
-- 		"pylsp", -- python
-- 		"sqls", --sql
-- 		"tsserver", -- typescript
-- 	},
-- }
