-- https://github.com/nvim-treesitter/nvim-treesitter
require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"bash",
		"fish",
		"graphql",
		"hcl",
		"http",
		"javascript",
		"json",
		"json5",
		"lua",
		"markdown",
		"python",
		"sql",
		"tsv",
		"tsx",
		"typescript",
		"vim",
		"vimdoc",
		"xml",
		"yaml",
	},
	-- sync_install = false,
	-- auto_install = true,
	-- ignore_install = {},
	highlight = {
		enable = true,
	},
})
