[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
    command! -bang -nargs=* Rg
      \ call fzf#vim#grep(
      \   'rg --line-number --no-heading '.shellescape(<q-args>),
	  \   0,
      \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap')
	  \ )
'''

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'heavenshell/vim-jsdoc'

[[plugins]]
repo = 'carlitux/deoplete-ternjs'

[[plugins]]
repo = 'davidhalter/jedi'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'vim-scripts/dbext.vim'
